# Generated by Django 5.1.4 on 2024-12-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
            preserve_default=False,
        ),
    ]
